eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: producer
  rabbitmq:
    host: 217.0.0.1
    port: 5672
    username:
    password: