eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: consumer
  rabbitmq:
    host: 217.0.0.1
    port: 5672
    username:
    password:

